dist: trusty
language: node_js

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint && yarn test

before_deploy:
  - yarn build

deploy:
  provider: npm
  email: wil@wilwilsman.com
  api_key:
    secure: "fhGMUdbVZQcqbn3iQHq5pAjMBbctrnlx02GVHn/5s/1R+XisOt/PJzWB+NeQ22roc7riycxHKxuchXdHHKV6AKrKsMdtL4EGSHb2VZtz31miP7/GvuNIhYWqhSw0+A6c/smvElMlzrF0P6AnVc9Fqf1CWfwiNBf7LuCmCtTI4WWWXEdj54rfXERtgYJX382U6GXFvGJx+iBZWT6qrcVpcS+BXacVxvYwXDg8LjGKLToIVxTuCeAiMKW9bOizoSbuDS1dD2N3IPYp8OsiMyzVpNEgUHq3FJM1EJlq7zoJ3z9ijiOkqohP8puQfOMlJYuCqssYv03Bs9IHP7jsVEfWXlJwvr0P7wZtkg8W4CJOf3pacB3DOCscXjncuAS6msN1bHrCVwLcJoScbFlw35O0mn6utfvfRFTLQZHRVwyE01qxFSkB4Ushjs9sPfIN91PDvF5Gbjb3xMS+9Xryupp47GL2YES3VSryNnVLzxCjcterJ8FSSYQXSALSny0JpJP0fc/ldi63Es/GFHn6XPrnIilOYN4Z2Tg+26Cb/i4yZshRLnKdPQObM5xQAGckxUETDxmtmHIBLuzNAZOVPsJMpnxzji2pg+CrhUYLF1bDrgFbLIGcBQgCx807b7L0eReWIrrq8qP3ZJFkyiH9QVLwIPoOu7avf/0YrU9By/T4Eto="
  on:
    tags: true
    branch: master
  skip_cleanup: true
